services:
  postgres:
    image: postgis/postgis:18-3.6
    hostname: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE:-stocks}
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    image: redis:7
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
