{
 "title": "HTTP Application Metrics",
 "tags": [
  "stocks-api",
  "http",
  "requests",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"http_request_count\" and r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 1m, fn: sum)\n |> fill(value: 0.0)\n |> last()"
    }
   ]
  },
  {
   "title": "P95 latency (Application layer)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"http_request_duration_ms\" and r._field == \"value\")\n  |> group()\n  |> quantile(q: 0.95)"
    }
   ]
  },
  {
   "title": "Error rate %",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "reqs = from(bucket: v.defaultBucket) |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"http_request_count\") |> aggregateWindow(every: v.windowPeriod, fn: sum) |> group()\n\nerrs = from(bucket: v.defaultBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"http_error_count\") |> aggregateWindow(every: v.windowPeriod, fn: sum) |> group()\n\njoin(tables: {req: reqs, err: errs}, on: [\"_time\"])\n  |> map(fn: (r) => ({ _time: r._time, _value: if r._value_req > 0.0 then (float(v: r._value_err) / float(v: r._value_req)) * 100.0 else 0.0 }))\n  |> last()"
    }
   ]
  },
  {
   "title": "HTTP Requests / sec (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_request_count\" and r._field == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> fill(column: \"_value\", value: 0.0)\n  |> yield(name: \"rps\")"
    }
   ]
  },
  {
   "title": "Application latency (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "base = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_request_duration_ms\" and r._field == \"value\")\n\np50 = base \n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> quantile(q: 0.50), createEmpty: false)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, percentile: \"p50\" }))\n\np95 = base \n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> quantile(q: 0.95), createEmpty: false)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, percentile: \"p95\" }))\n\np99 = base \n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> quantile(q: 0.99), createEmpty: false)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, percentile: \"p99\" }))\n\nunion(tables: [p50, p95, p99])\n  |> group(columns: [\"percentile\"])"
    }
   ]
  },
  {
   "title": "HTTP Errors / sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_error_count\" and r._field == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> fill(column: \"_value\", value: 0.0)\n  |> yield(name: \"errors\")"
    }
   ]
  },
  {
   "title": "Cache Distribution (Total Count)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 32, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_cache_hits\" and r._field == \"value\")\n  |> group(columns: [\"status\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"absolute_counts\")"
    }
   ]
  }
 ]
}